python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_1/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_2/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_3/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_4/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_5/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_6/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_7/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_8/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_9/_settings.xml
python3 /home/mohacsi/Desktop/optimizer/optimizer/neuroptimus.py -c /home/mohacsi/Desktop/optimizer/ALLtest/optimizer_multirun/hh_pas_surrogatensga2-inspyrednsga2-inspyred_10/_settings.xml
